services:
  db:
    image: postgres:16
    container_name: subscriptions_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscriptions
    ports:
      - "5433:5432"
    
